#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ietf-i2nsf-analytics-interface.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module ietf-i2nsf-analytics-interface.yang


class ns(object):
    hash = 255936380

    id = "urn:ietf:params:xml:ns:yang:ietf-i2nsf-analytics-interface"

    uri = "urn:ietf:params:xml:ns:yang:ietf-i2nsf-analytics-interface"

    prefix = "i2nsfai"

    i2nsfai_req_method = 924512213
    i2nsfai_req_method_ = "req-method"
    i2nsfai_hardware_alarm = 628598332
    i2nsfai_hardware_alarm_ = "hardware-alarm"
    i2nsfai_attack_type = 1421852857
    i2nsfai_attack_type_ = "attack-type"
    i2nsfai_virus_detected = 893229667
    i2nsfai_virus_detected_ = "virus-detected"
    i2nsfai_os = 398384563
    i2nsfai_os_ = "os"
    i2nsfai_up = 1
    i2nsfai_up_ = "up"
    i2nsfai_interface_id = 805894379
    i2nsfai_interface_id_ = "interface-id"
    i2nsfai_file_type = 1206426190
    i2nsfai_file_type_ = "file-type"
    i2nsfai_cookies = 303249651
    i2nsfai_cookies_ = "cookies"
    i2nsfai_congested = 3
    i2nsfai_congested_ = "congested"
    i2nsfai_app = 1820663438
    i2nsfai_app_ = "app"
    i2nsfai_host = 1711485895
    i2nsfai_host_ = "host"
    i2nsfai_testing = 4
    i2nsfai_testing_ = "testing"
    i2nsfai_attack_dst_ip = 1108056505
    i2nsfai_attack_dst_ip_ = "attack-dst-ip"
    i2nsfai_time = 190171445
    i2nsfai_time_ = "time"
    i2nsfai_lower_layer_down = 8
    i2nsfai_lower_layer_down_ = "lower-layer-down"
    i2nsfai_user_agent = 1242907368
    i2nsfai_user_agent_ = "user-agent"
    i2nsfai_solution = 588503613
    i2nsfai_solution_ = "solution"
    i2nsfai_nsf_name = 59165401
    i2nsfai_nsf_name_ = "nsf-name"
    i2nsfai_alarm_type = 1671421893
    i2nsfai_alarm_type_ = "alarm-type"
    i2nsfai_cpu_alarm = 727651103
    i2nsfai_cpu_alarm_ = "cpu-alarm"
    i2nsfai_memory_alarm = 1670602543
    i2nsfai_memory_alarm_ = "memory-alarm"
    i2nsfai_web_attack_detected = 1480702014
    i2nsfai_web_attack_detected_ = "web-attack-detected"
    i2nsfai_usage = 1333989540
    i2nsfai_usage_ = "usage"
    i2nsfai_req_user_agent = 2132563188
    i2nsfai_req_user_agent_ = "req-user-agent"
    i2nsfai_disk_id = 701137991
    i2nsfai_disk_id_ = "disk-id"
    i2nsfai_virus_type = 525465882
    i2nsfai_virus_type_ = "virus-type"
    i2nsfai_intrusion_detected = 1606940151
    i2nsfai_intrusion_detected_ = "intrusion-detected"
    i2nsfai_attack_dst_port = 359613874
    i2nsfai_attack_dst_port_ = "attack-dst-port"
    i2nsfai_req_host = 276799838
    i2nsfai_req_host_ = "req-host"
    i2nsfai_voip_vocn_detected = 1520996822
    i2nsfai_voip_vocn_detected_ = "voip-vocn-detected"
    i2nsfai_down = 2
    i2nsfai_down_ = "down"
    i2nsfai_i2nsf_feedback_information = 1364670364
    i2nsfai_i2nsf_feedback_information_ = "i2nsf-feedback-information"
    i2nsfai_problem = 1901342902
    i2nsfai_problem_ = "problem"
    i2nsfai_attack_src_ip = 558305519
    i2nsfai_attack_src_ip_ = "attack-src-ip"
    i2nsfai_not_present = 7
    i2nsfai_not_present_ = "not-present"
    i2nsfai_message = 1674281495
    i2nsfai_message_ = "message"
    i2nsfai_response_code = 9013985
    i2nsfai_response_code_ = "response-code"
    i2nsfai_attack_src_port = 788675816
    i2nsfai_attack_src_port_ = "attack-src-port"
    i2nsfai_interface_alarm = 1980185781
    i2nsfai_interface_alarm_ = "interface-alarm"
    i2nsfai_file_name = 1824330763
    i2nsfai_file_name_ = "file-name"
    i2nsfai_destination_voice_id = 2035779950
    i2nsfai_destination_voice_id_ = "destination-voice-id"
    i2nsfai_source_voice_id = 622969059
    i2nsfai_source_voice_id_ = "source-voice-id"
    i2nsfai_duration = 686902226
    i2nsfai_duration_ = "duration"
    i2nsfai_attack_detection = 382068228
    i2nsfai_attack_detection_ = "attack-detection"
    i2nsfai_component_name = 604739785
    i2nsfai_component_name_ = "component-name"
    i2nsfai_disk_alarm = 434463387
    i2nsfai_disk_alarm_ = "disk-alarm"
    i2nsfai_req_uri = 33515346
    i2nsfai_req_uri_ = "req-uri"
    i2nsfai_virus_name = 2038112307
    i2nsfai_virus_name_ = "virus-name"
    i2nsfai_unknown = 5
    i2nsfai_unknown_ = "unknown"
    i2nsfai_protocol = 943257313
    i2nsfai_protocol_ = "protocol"
    i2nsfai_dormant = 6
    i2nsfai_dormant_ = "dormant"
    i2nsfai_interface_state = 715994464
    i2nsfai_interface_state_ = "interface-state"
    i2nsfai_ddos_detected = 1107716019
    i2nsfai_ddos_detected_ = "ddos-detected"
    i2nsfai_language = 2034330531
    i2nsfai_language_ = "language"
