# -*- coding: utf-8 -*-
from operator import attrgetter
from pyangbind.lib.yangtypes import RestrictedPrecisionDecimalType
from pyangbind.lib.yangtypes import RestrictedClassType
from pyangbind.lib.yangtypes import TypedListType
from pyangbind.lib.yangtypes import YANGBool
from pyangbind.lib.yangtypes import YANGListType
from pyangbind.lib.yangtypes import YANGDynClass
from pyangbind.lib.yangtypes import ReferenceType
from pyangbind.lib.base import PybindBase
from collections import OrderedDict
from decimal import Decimal
from bitarray import bitarray
import six

# PY3 support of some PY2 keywords (needs improved)
if six.PY3:
  import builtins as __builtin__
  long = int
elif six.PY2:
  import __builtin__

from . import query_nsf_capability
class input(PybindBase):
  """
  This class was auto-generated by the PythonClass plugin for PYANG
  from YANG module ietf-i2nsf-registration-interface - based on the path /ietf_i2nsf_registration_interface_rpc/nsf-capability-registration/input. Each member element of
  the container is represented as a class variable - with a specific
  YANG type.
  """
  __slots__ = ('_path_helper', '_extmethods', '__query_nsf_capability',)

  _yang_name = 'input'

  _pybind_generated_by = 'container'

  def __init__(self, *args, **kwargs):

    self._path_helper = False

    self._extmethods = False
    self.__query_nsf_capability = YANGDynClass(base=query_nsf_capability.query_nsf_capability, is_container='container', yang_name="query-nsf-capability", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=False, extensions=None, namespace='urn:ietf:params:xml:ns:yang:ietf-i2nsf-registration-interface', defining_module='ietf-i2nsf-registration-interface', yang_type='container', is_config=True)

    load = kwargs.pop("load", None)
    if args:
      if len(args) > 1:
        raise TypeError("cannot create a YANG container with >1 argument")
      all_attr = True
      for e in self._pyangbind_elements:
        if not hasattr(args[0], e):
          all_attr = False
          break
      if not all_attr:
        raise ValueError("Supplied object did not have the correct attributes")
      for e in self._pyangbind_elements:
        nobj = getattr(args[0], e)
        if nobj._changed() is False:
          continue
        setmethod = getattr(self, "_set_%s" % e)
        if load is None:
          setmethod(getattr(args[0], e))
        else:
          setmethod(getattr(args[0], e), load=load)

  def _path(self):
    if hasattr(self, "_parent"):
      return self._parent._path()+[self._yang_name]
    else:
      return ['ietf_i2nsf_registration_interface_rpc', 'nsf-capability-registration', 'input']

  def _get_query_nsf_capability(self):
    """
    Getter method for query_nsf_capability, mapped from YANG variable /ietf_i2nsf_registration_interface_rpc/nsf_capability_registration/input/query_nsf_capability (container)

    YANG Description: The query used to request NSFs. The specified
capabilities in this field restrict the output field.
    """
    return self.__query_nsf_capability
      
  def _set_query_nsf_capability(self, v, load=False):
    """
    Setter method for query_nsf_capability, mapped from YANG variable /ietf_i2nsf_registration_interface_rpc/nsf_capability_registration/input/query_nsf_capability (container)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_query_nsf_capability is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_query_nsf_capability() directly.

    YANG Description: The query used to request NSFs. The specified
capabilities in this field restrict the output field.
    """
    if hasattr(v, "_utype"):
      v = v._utype(v)
    try:
      t = YANGDynClass(v,base=query_nsf_capability.query_nsf_capability, is_container='container', yang_name="query-nsf-capability", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=False, extensions=None, namespace='urn:ietf:params:xml:ns:yang:ietf-i2nsf-registration-interface', defining_module='ietf-i2nsf-registration-interface', yang_type='container', is_config=True)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """query_nsf_capability must be of a type compatible with container""",
          'defined-type': "container",
          'generated-type': """YANGDynClass(base=query_nsf_capability.query_nsf_capability, is_container='container', yang_name="query-nsf-capability", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=False, extensions=None, namespace='urn:ietf:params:xml:ns:yang:ietf-i2nsf-registration-interface', defining_module='ietf-i2nsf-registration-interface', yang_type='container', is_config=True)""",
        })

    self.__query_nsf_capability = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_query_nsf_capability(self):
    self.__query_nsf_capability = YANGDynClass(base=query_nsf_capability.query_nsf_capability, is_container='container', yang_name="query-nsf-capability", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=False, extensions=None, namespace='urn:ietf:params:xml:ns:yang:ietf-i2nsf-registration-interface', defining_module='ietf-i2nsf-registration-interface', yang_type='container', is_config=True)

  query_nsf_capability = __builtin__.property(_get_query_nsf_capability, _set_query_nsf_capability)


  _pyangbind_elements = OrderedDict([('query_nsf_capability', query_nsf_capability), ])


