/*
 * dp documentation to be included in _dp.c
 */

#define EVENTS_MODULE_DOCSTR(PROD) \
"Low level module for subscribing to " PROD " event notifications.\n\n"\
\
"This module is used to connect to " PROD " and subscribe to certain\n"\
"events generated by " PROD ". The API to receive events from " PROD " is a\n"\
"socket based API whereby the application connects to " PROD " and receives\n"\
"events on a socket. See also the Notifications chapter in the User Guide.\n"\
"The program misc/notifications/confd_notifications.c in the examples\n"\
"collection illustrates subscription and processing for all these events,\n"\
"and can also be used standalone in a development environment to monitor\n"\
PROD " events.\n\n"\
\
"This documentation should be read together with the confd_lib_events(3) "\
"man page."

#define DOC(name) PyDoc_STRVAR(_events_ ## name ## __doc__,

/* ------------------------------------------------------------------------- */
DOC(notifications_connect)
/* ------------------------------------------------------------------------- */
"notifications_connect(sock, mask, ip, port, path) -> None\n\n"

"This function creates a notification socket.\n\n"

"Keyword arguments:\n\n"

"* sock -- a Python socket instance\n"
"* mask -- a bitmask of one or several notification type values\n"
"* ip -- the ip address if socket is AF_INET (optional)\n"
"* port -- the port if socket is AF_INET (optional)\n"
"* path -- a filename if socket is AF_UNIX (optional)."
);

/* ------------------------------------------------------------------------- */
DOC(notifications_connect2)
/* ------------------------------------------------------------------------- */
"notifications_connect2(sock, mask, data, ip, port, path) -> None\n\n"

"This variant of notifications_connect is required if we wish to subscribe\n"
"to NOTIF_HEARTBEAT, NOTIF_HEALTH_CHECK, or NOTIF_STREAM_EVENT events.\n\n"

"Keyword arguments:\n\n"

"* sock -- a Python socket instance\n"
"* mask -- a bitmask of one or several notification type values\n"
"* data -- a _events.NotificationsData instance\n"
"* ip -- the ip address if socket is AF_INET (optional)\n"
"* port -- the port if socket is AF_INET (optional)\n"
"* path -- a filename if socket is AF_UNIX (optional)"
);

/* ------------------------------------------------------------------------- */
DOC(read_notification)
/* ------------------------------------------------------------------------- */
"read_notification(sock) -> dict\n\n"

"The application is responsible for polling the notification socket. Once\n"
"data is available to be read on the socket the application must call\n"
"read_notification() to read the data from the socket. On success a\n"
"dictionary containing notification information will be returned (see below)."
"\n\n"

"Keyword arguments:\n\n"

"* sock -- a previously connected notification socket\n\n"

"On success the returned dict will contain information corresponding to the\n"
"c struct confd_notification. The notification type is accessible through\n"
"the 'type' key. The remaining information will be different depending on\n"
"which type of notification this is (described below).\n\n"

"Keys for type NOTIF_AUDIT (struct confd_audit_notification):\n\n"

"*   logno\n"
"*   user\n"
"*   msg\n"
"*   usid\n\n"

"Keys for type NOTIF_DAEMON, NOTIF_NETCONF, NOTIF_DEVEL, NOTIF_JSONRPC,\n"
"NOTIF_WEBUI, or NOTIF_TAKEOVER_SYSLOG (struct confd_syslog_notification):\n\n"

"*   prio\n"
"*   logno\n"
"*   msg\n\n"

"Keys for type NOTIF_COMMIT_SIMPLE (struct confd_commit_notification):\n\n"

"*   database\n"
"*   diff_available\n"
"*   flags\n"
"*   uinfo\n\n"

"Keys for type NOTIF_COMMIT_DIFF (struct confd_commit_diff_notification):\n\n"

"*   database\n"
"*   flags\n"
"*   uinfo\n"
"*   tctx\n"
"*   label (optional)\n"
"*   comment (optional)\n\n"

"Keys for type NOTIF_USER_SESSION (struct confd_user_sess_notification):\n\n"

"*   type\n"
"*   uinfo\n"
"*   database\n\n"

"Keys for type NOTIF_HA_INFO (struct confd_ha_notification):\n\n"

"*   type (1)\n"
"*   noprimary - if (1) is HA_INFO_NOPRIMARY\n"
"*   secondary_died - if (1) is HA_INFO_SECONDARY_DIED (see below)\n"
"*   secondary_arrived - if (1) is HA_INFO_SECONDARY_ARRIVED (see below)\n"
"*   cdb_initialized_by_copy - if (1) is HA_INFO_SECONDARY_INITIALIZED\n"
"*   besecondary_result - if (1) is HA_INFO_BESECONDARY_RESULT\n\n"

"If secondary_died or secondary_arrived is present they will in turn contain\n"
"a dictionary with the following keys:\n\n"

"*   nodeid\n"
"*   af (1)\n"
"*   ip4 - if (1) is AF_INET\n"
"*   ip6 - if (1) is AF_INET6\n"
"*   str - if (1) if AF_UNSPEC\n\n"

"Keys for type NOTIF_SUBAGENT_INFO (struct confd_subagent_notification):\n\n"

"*   type\n"
"*   name\n\n"

"Keys for type NOTIF_COMMIT_FAILED (struct confd_commit_failed_notification):"
"\n\n"

"*   provider (1)\n"
"*   dbname\n"
"*   port - if (1) is DP_NETCONF\n"
"*   af (2) - if (1) is DP_NETCONF\n"
"*   ip4 - if (2) is AF_INET\n"
"*   ip6 - if (2) is AF_INET6\n"
"*   daemon_name - if (1) is DP_EXTERNAL\n\n"

"Keys for type NOTIF_SNMPA (struct confd_snmpa_notification):\n\n"

"*   pdu_type (1)\n"
"*   request_id\n"
"*   error_status\n"
"*   error_index\n"
"*   port\n"
"*   af (2)\n"
"*   ip4 - if (3) is AF_INET\n"
"*   ip6 - if (3) is AF_INET6\n"
"*   vb (optional)\n"
"*   generic_trap - if (1) is SNMPA_PDU_V1TRAP\n"
"*   specific_trap - if (1) is SNMPA_PDU_V1TRAP\n"
"*   time_stamp - if (1) is SNMPA_PDU_V1TRAP\n"
"*   enterprise - if (1) is SNMPA_PDU_V1TRAP (optional)\n\n"

"Keys for type NOTIF_FORWARD_INFO (struct confd_forward_notification):\n\n"

"*   type\n"
"*   target\n"
"*   uinfo\n\n"

"Keys for type NOTIF_CONFIRMED_COMMIT\n"
" (struct confd_confirmed_commit_notification):\n\n"

"*   type\n"
"*   timeout\n"
"*   uinfo\n\n"

"Keys for type NOTIF_UPGRADE_EVENT (struct confd_upgrade_notification):\n\n"

"*   event\n\n"

"Keys for type NOTIF_COMMIT_PROGRESS and NOTIF_PROGRESS\n"
" (struct confd_progress_notification):\n\n"

"*   type (1)\n"
"*   timestamp\n"
"*   duration if (1) is CONFD_PROGRESS_STOP\n"
"*   usid\n"
"*   tid\n"
"*   datastore\n"
"*   context\n"
"*   phase (optional)\n"
"*   msg\n"
"*   annotation (optional)\n"
#ifdef CONFD_PY_PRODUCT_NCS
"*   service (optional)\n"
"*   service_phase (optional)\n"
"*   commit_queue_id (optional)\n"
"*   node (optional)\n"
"*   device (optional)\n"
"*   device_phase (optional)\n"
"*   package (optional)\n"
#endif
"\n"

#ifdef CONFD_PY_PRODUCT_NCS
"Keys for type NOTIF_STREAM_EVENT (struct confd_stream_notification):\n\n"

"*   type (1)\n"
"*   error - if (1) is STREAM_REPLAY_FAILED\n"
"*   event_time - if (1) is STREAM_NOTIFICATION_EVENT\n"
"*   values - if (1) is STREAM_NOTIFICATION_EVENT\n\n"

"Keys for type NOTIF_CQ_PROGRESS (struct ncs_cq_progress_notification):\n\n"

"*   type\n"
"*   timestamp\n"
"*   cq_tag\n"
"*   cq_id\n"
"*   completed_devices (optional)\n"
"*   transient_devices (optional)\n"
"*   failed_devices (optional)\n"
"*   failed_reasons - if failed_devices is present\n"
"*   completed_services (optional)\n"
"*   completed_services_completed_devices - if completed_services is present\n"
"*   failed_services (optional)\n"
"*   failed_services_completed_devices - if failed_services is present\n"
"*   failed_services_failed_devices - if failed_services is present\n\n"

"Keys for type NOTIF_CALL_HOME_INFO (struct ncs_call_home_notification):"
"\n\n"

"*   type (1)\n"
"*   device - if (1) is CALL_HOME_DEVICE_CONNECTED\n"
"*   af (2)\n"
"*   ip4 - if (2) is AF_INET\n"
"*   ip6 - if (2) is AF_INET6\n"
"*   port\n"
"*   ssh_host_key\n"
"*   ssh_key_alg\n\n"
#endif
);

/* ------------------------------------------------------------------------- */
DOC(diff_notification_done)
/* ------------------------------------------------------------------------- */
"diff_notification_done(sock, tctx) -> None\n\n"

"If the received event was NOTIF_COMMIT_DIFF it is important that we call\n"
"this function when we are done reading the transaction diffs over MAAPI.\n"
"The transaction is hanging until this function gets called. This function\n"
"also releases memory associated to the transaction in the library.\n\n"

"Keyword arguments:\n\n"

"* sock -- a previously connected notification socket\n"
"* tctx -- a transaction context"
);

/* ------------------------------------------------------------------------- */
DOC(sync_audit_notification)
/* ------------------------------------------------------------------------- */
"sync_audit_notification(sock, usid) -> None\n\n"

"If the received event was NOTIF_AUDIT, and we are subscribing to\n"
"notifications with the flag NOTIF_AUDIT_SYNC, this function must be called\n"
"when we are done processing the notification. The user session is hanging\n"
"until this function gets called.\n\n"

"Keyword arguments:\n\n"

"* sock -- a previously connected notification socket\n"
"* usid -- the user session id"
);

/* ------------------------------------------------------------------------- */
DOC(sync_ha_notification)
/* ------------------------------------------------------------------------- */
"sync_ha_notification(sock) -> None\n\n"

"If the received event was NOTIF_HA_INFO, and we are subscribing to\n"
"notifications with the flag NOTIF_HA_INFO_SYNC, this function must be\n"
"called when we are done processing the notification. All HA processing is\n"
"blocked until this function gets called.\n\n"

"Keyword arguments:\n\n"

"* sock -- a previously connected notification socket"
);

/* ------------------------------------------------------------------------- */
#ifdef CONFD_PY_PRODUCT_NCS
DOC(sync_audit_network_notification)
/* ------------------------------------------------------------------------- */
"sync_audit_network_notification(sock, usid) -> None\n\n"

"If the received event was NOTIF_AUDIT_NETWORK, and we are subscribing to\n"
"notifications with the flag NOTIF_AUDIT_NETWORK_SYNC, this function must be\n"
"called when we are done processing the notification. The user session is\n"
"hanging until this function gets called.\n\n"

"Keyword arguments:\n\n"

"* sock -- a previously connected notification socket\n"
"* usid -- the user session id"
);
#endif

#undef DOC
