/*

This file is generated by gen-constants.py. 2023-03-24 20:13:03.572121

Edit at your own risk!!!!

*/


/* /lab/build/tailf-src/confd-basic.confd-8.0.4-x86_64/confd_dir/include/confd_ha.h */

/* Generated by gcc -w -E -DCONFD_C_PRODUCT_CONFD -dD - command */

/* enum confd_ha_status_state { */
     ADD_CONST(CONFD_HA_STATE_NONE, "STATE_NONE");
     ADD_CONST(CONFD_HA_STATE_SECONDARY, "STATE_SECONDARY");
     ADD_CONST(CONFD_HA_STATE_PRIMARY, "STATE_PRIMARY");
     ADD_CONST(CONFD_HA_STATE_SECONDARY_RELAY, "STATE_SECONDARY_RELAY");
     ADD_CONST(CONFD_HA_STATE_SLAVE, "STATE_SLAVE");
     ADD_CONST(CONFD_HA_STATE_MASTER, "STATE_MASTER");
     ADD_CONST(CONFD_HA_STATE_SLAVE_RELAY, "STATE_SLAVE_RELAY");
/* }; */
